version: '3.9'


services:

  db:
    container_name: postgres_db_container
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    restart: unless-stopped
    env_file:
      - env/.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    env_file:
      - env/.env
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

volumes:
  postgres_volume:
