version: '3.9'

services:
  stock_app:
    build: ./stocks_products
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/stock_app/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex030120
      - POSTGRES_DB=stock
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/stock_app/staticfiles/
    ports:
      - 1337:80
    depends_on:
      - stock_app
volumes:
  postgres_volume:
  static_volume: